# Name: Sravan Bhamidipati
# Date: 19th October, 2012
# Purpose: Config file of Twitter Dedupe application.


application: twitterdedupe
version: 1b
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: jinja2
  version: "2.6"
- name: setuptools
  version: "0.6c11"

handlers:
- url: /.*
  script: main.app
  secure: always