# Name: Sravan Bhamidipati
# Date: 17th October, 2012
# Purpose: Config file of Twitter Dedupe application.


application: twitterdedupe
version: 1b
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /.*
  script: main.app
  secure: always
